### ISSUE TITLE
Getting 6 Errors

### ISSUE THREAD

**Issue by EddieSoloProjects** [FriendsOfSpatial/MMORPGController#1]
Any chance that we could get a zip file of this already put into the default stater project. I am fairly new at SpatialOs and I have no idea how to fix the 6 errors I am getting or even why they are there.

**Comment by chrisisbeef** [comment]
This isn't quite ready for consumption yet - it's like slow-cooked pork, you don't want to start eating it before it's done :) 

That being said - I'll see what I can do about getting the master branch to a stable state this afternoon

**Comment by chrisisbeef** [comment]
@EddieSoloProjects - the last push should be a relatively stable and functional version. To use - just download an unzip in your project directory; then follow the simple instructions at the beginning of the readme. I'll continue to update the readme with additional context in the coming days as I have time.

**Comment by EddieSoloProjects** [comment]
Thanks I will try it tonight :)
